---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  NAS_ADDR: 192.168.1.10
  METALLB_LB_RANGE: 192.168.1.20-192.168.1.40
  SVC_INFLUXDB_HOME_ASSISTANT_ADDR: 192.168.1.20
  SVC_MOSQUITTO_ADDR: 192.168.1.21
  SVC_UNIFI_ADDR: 192.168.1.22
  SVC_ADGUARD_ADDR: 192.168.1.23
  SVC_LINKY_INFLUXDB_ADDR: 192.168.1.24
  SVC_TRAEFIK_ADDR: 192.168.1.25
  SVC_TVHEADEND_ADDR: 192.168.1.26
  SVC_TRANSMISSION_ADDR: 192.168.1.27
  SVC_JOAL_ADDR: 192.168.1.28
  SVC_JELLYFIN_ADDR: 192.168.1.29
  SVC_SCRYPTED_ADDR: 192.168.1.30
  SVC_HOMEBRIDGE_ADDR: 192.168.1.31
  SVC_HOME_ASSISTANT_ADDR: 192.168.1.32
  SVC_NAVIDROME_ADDR: 192.168.1.33
  SVC_MUSIC_ASSISTANT_ADDR: 192.168.1.34
  SVC_MINIO_ADDR: 192.168.1.35
