apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - networking
  - vaultwarden
  - mosquitto
  - adguard-home
  - tydom2mqtt
  - home-assistant
  - unifi
  - teslamate
  - node-red
  - heimdall
  - esphome
  - influxdb-home-assistant
  - zigbee2mqtt
  - teleinfo2mqtt
  - tvheadend
  - system-upgrade
  - restic
  - sonarr
  - radarr
  - prowlarr
  - transmission
  - joal
  - obsidian-couchdb
  - unpoller
  - jellyfin
  - jellyseerr
  - scrypted
  - lidarr
  - navidrome
  - flaresolverr
  - uptime-kuma
  - minio
  - spotdl
  - backrest
  - aiconnect
  - memos
  - tesla-fleet
  - ygege
  - music-assistant
  - slskd
  - yubal
  - shopping-cards
