apiVersion: v1
kind: ConfigMap
metadata:
  name: tesla-fleet-nginx-configmap
  namespace: tesla-fleet
data:
  default.conf: |
    server {
      listen 80;
      server_name tesla-fleet.home.sebastien-laporte.fr;
      root /var/www/tesla;

      location / {
        try_files $uri $uri/ =404;
      }
    }